version: '3.8'

services:
    app:
        build: .
        container_name: marketoo_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - node
        networks:
            - marketoo_network

    web:
        image: nginx:alpine
        container_name: marketoo_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - marketoo_network

    node:
        image: node:22
        container_name: marketoo_node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: [ "npm", "install" ]
        networks:
            - marketoo_network

networks:
    marketoo_network:
        driver: bridge
